apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: envio
  annotations:
    kubernetes.io/ingress.class: "$NLB" #nginx / prod-nginx / dev-nginx
  labels:
    app: envio
  namespace: $NAMESPACE
spec:
  rules:
    - http:
        paths:
        - path: /envio
          backend:
            serviceName: envio
            servicePort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: envio
  labels:
    app: envio
    service: envio
  namespace: $NAMESPACE
spec:
  type: LoadBalancer
  selector:
    component: envio
  ports:
  - name: envio
    port: 4000
    targetPort: 3002

